# Created using wingetcreate 1.1.2.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.2.0.schema.json

PackageIdentifier: Pivot.PivotAnimator
PackageVersion: 5.1.23
PackageLocale: en-US
Publisher: Pivot
PackageName: Pivot Animator
License: unknown
Copyright: Copyright Pivotstick
ShortDescription: PivotStick
ManifestType: defaultLocale
ManifestVersion: 1.2.0

